import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/store/ReduxProvider';
import AuthInitProvider from './AuthInitProvider';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`${montserrat.variable}`}>
          <AuthInitProvider>{children}</AuthInitProvider>
        </body>
      </html>
    </ReduxProvider>
  );
}
